### PR TITLE
SearXNG support - urls need to be changed per instance

### PR DESCRIPTION
**Pull request by danielyrovas**
No need to merge this (but it should be safe as it doesn't break the normal search injection and just adds a few SearX instances as examples). This is for the SearXNG fork of SearX.
To use SearX the line here needs to select the `#sidebar_results` id

> https://github.com/Fivefold/linkding-injector/blob/fdb713bd3af7f47497dd561a54d4d94ca5e3f8b8/src/searchInjection.js#L117-L122

and this needs to match the host of the site somewhere
 

> https://github.com/Fivefold/linkding-injector/blob/fdb713bd3af7f47497dd561a54d4d94ca5e3f8b8/src/searchInjection.js#L22-L26

### CODE REVIEW

**Comment by Fivefold** [comment]
Thank you. I won't merge this because I would consider proper SearX support supporting as many publix SearX instances _as well_ as self-hosted ones. I think this isn't possible, as mentioned in #2

I will keep this open though so people can discover it and add their own support if they wish to.

**Comment by danielyrovas** [comment]
> I will keep this open though so people can discover it and add their own support if they wish to.

Yeah that's what I was thinking. Thanks for all your help. All I can say is signing add-ons is super frustrating. Not looking forward to doing that every time I need to update it lol.

**Comment by Fivefold** [comment]
I agree but it's for security reasons. You could work around this by disabling the xpi signature check (at your own risk - better not install any other extensions that are not from addons.mozilla.org then). Check the last section [here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox).

**Comment by danielyrovas** [comment]
Yeah I saw that, I think its good experience for me to have anyway if I develop some extensions in the future.

**Comment by Fivefold** [comment]
Hey @danielyrovas there is now official support for SearXNG in v1.3.0! If you use firefox you can already check it out, the chrome extension is still under review but should be published within the next days.

**Comment by danielyrovas** [comment]
Thank you @Fivefold, I've got the Firefox addon and its working great. Awesome work.

**Pull request closed without merging**
